# Generated by Django 4.2.7 on 2023-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_ormuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="ormuser",
            name="token",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
