# Generated by Django 4.2.7 on 2024-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_ormuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ormuser",
            name="password",
            field=models.BinaryField(),
        ),
    ]
