# Generated by Django 4.2.7 on 2024-01-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_ormuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="ormuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Participant", "Participant"),
                    ("Organizer", "Organizer"),
                    ("OrganizerAdmin", "Organizer admin"),
                ],
                default="Participant",
                max_length=120,
            ),
        ),
    ]
