# Generated by Django 4.2.7 on 2024-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_ormuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="ormuser",
            name="alimentary_restrictions",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="current_job_role",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="date_of_birth",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="degree",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="devpost",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="expected_graduation",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("NO_BINARY", "No-binary"),
                    ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                ],
                default="Prefer not to say",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="github",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="linkedin",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="study",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="tshirt",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="M",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="university",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="webpage",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ormuser",
            name="work",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ormuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PARTICIPANT", "Participant"),
                    ("ORGANIZER", "Organizer"),
                    ("ORGANIZER_ADMIN", "Organizer admin"),
                ],
                default="Participant",
                max_length=120,
            ),
        ),
    ]
