# Generated by Django 4.2.7 on 2024-01-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_ormuser_alimentary_restrictions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ormuser",
            name="date_of_birth",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ormuser",
            name="expected_graduation",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ormuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                    ("NO_BINARY", "No-binary"),
                    ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                ],
                default=None,
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ormuser",
            name="tshirt",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default=None,
                max_length=120,
                null=True,
            ),
        ),
    ]
