# Generated by Django 4.2.7 on 2024-01-08 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_ormapplication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ormapplication",
            old_name="event_id",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="ormapplication",
            old_name="user_id",
            new_name="user",
        ),
    ]
