# Generated by Django 4.2.7 on 2024-01-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_ormeventapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="ormeventapplication",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
