# Generated by Django 4.2.7 on 2024-01-09 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_ormeventapplication_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ormeventapplication",
            name="deleted_at",
        ),
    ]
