# Generated by Django 4.2.7 on 2024-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_ormeventapplication_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ormevent",
            name="age_restrictions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ormevent",
            name="expected_attrition_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ormevent",
            name="max_participants",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ormevent",
            name="open_for_participants",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ormevent",
            name="students_only",
            field=models.BooleanField(default=False),
        ),
    ]
