# Generated by Django 4.2.7 on 2024-01-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_ormeventapplication_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ORMQuestion",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("OPTIONS", "Options"),
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                        ],
                        max_length=255,
                    ),
                ),
                ("options", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.ormevent"
                    ),
                ),
            ],
            options={
                "db_table": "question",
            },
        ),
    ]
