# Generated by Django 4.2.7 on 2024-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_ormquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ormquestion",
            name="options",
            field=models.CharField(max_length=255),
        ),
    ]
