# Generated by Django 4.2.7 on 2024-01-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_ormquestion_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ORMAnswers",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ormeventapplication",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.ormquestion",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
            },
        ),
    ]
