# Generated by Django 4.2.7 on 2024-01-17 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_ormanswers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ormanswers",
            unique_together={("question", "application")},
        ),
    ]
